
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dead_and_company_review_development

test:
  <<: *default
  database: dead_and_company_review_test


#
production:
  <<: *default
  database: dead_and_company_review_production
  username: setlist
  password: <%= ENV['SETLIST_DATABASE_PASSWORD'] %>
